### ISSUE TITLE
Add the extra in-development building blocks

### ISSUE THREAD

**Issue by rachellawson** [GovStackWorkingGroup/specifications#24]
Add the extra building blocks that are currently in development to the BB page on the main spec

**Comment by rachellawson** [comment]
@Ayushdidit could you possibly check the change request in gitbook that it

- [ ] only affects the development branch
- [ ] only affects the About Building Blocks Page
- [ ] adds each of the building blocks in a little expandable block with explanatory text 
- [ ] has no spelling errors :-)

**Comment by Ayushdidit** [comment]
Hi Rachel
- All BBs from wave 1, Workflow and Concent are linked on the about BB page. Each BB also has an expandable box with their desccriptions.
- There are no spelling errors on the about BB page.
