### ISSUE TITLE
Possibility to provide use cases

### ISSUE THREAD

**Issue by fretchen** [GovStackWorkingGroup/specifications#35]
**Is your feature request related to a problem? Please describe.**
I would like to suggest and provide use cases for the govstack system.

**Describe the solution you'd like**
Provide some template or guideline on how to provide them here, maybe even connect the dial catalogue with the github through some button.

**Describe alternatives you've considered**
Going through some rather complex internal meetings, which is however ... complex.

**Additional context**
Working on the topic in an financial cooperation context and would like to provide this point of view in a transparent fashion.

**Comment by rachellawson** [comment]
Hi @fretchen  and welcome to GovStack! 

Your offer to help with use-cases that are relevant to GovStack is really interesting and I'm sure I can help to connect you with the right people to begin that. Can you possibly describe one or two that you are aware of? That might help me to connect you to the right people. The specification crosses multiple areas with different people focusing on each.

**Comment by fretchen** [comment]
Hi,

thanks a lot. I was now trying to look for the use case on the GovStack website, however I found none and it only seemed to focus on Building Blocks. So Use Case are now mostly put together in the [Dial Catalogue](https://solutions.dial.community/use_cases/remote_learning) ?

Anyways, very frequent use cases come from the educational sector including TVET and there we often touch on topics of blended learning, EMIS, parent & teacher interaction, student & interaction, device control, registration etc. So they are related to the [mobile learning use case](https://solutions.dial.community/use_cases/remote_learning), but not really more than that I would say.

**Comment by rachellawson** [comment]
Ah! Good points there. 

The use cases we have used so far have indeed largely come from the Catalog of Digital Solutions but the plan is to involve more and more discovery of use cases in countries we work with. 

Still, improving the quality and relevance of use cases is always a goal. 

Also, that you had to guess where those use cases came from is relevant to improving the story we are telling on the website - and we have been around the project too g to notice the gaps. I think it is useful here to bring in  a colleague who is looking at the website.

**Comment by fretchen** [comment]
Ok, 

I am happy to provide feedback on the website. When it is clear how to contribute to use cases please feel free to get back to me here.

**Comment by rachellawson** [comment]
Hi @fretchen — the use cases will be appearing at https://govstack-global.atlassian.net/jira/software/c/projects/PRD/boards/25 and all work will take place there from now on. I’m closing this issue and inviting you to that Jira project…
